### PR TITLE
Hashing Passwords. First attempt.

### PR DESCRIPTION
**Pull request by yasserhussain1110**

### CODE REVIEW

**Comment by Oxyrus** [comment]
Great work @yasserhussain1110 , I have a question regarding your function. What happens when the changeset is invalid? Does it perform any encryption at all? The way I see it is that it encrypts the password, even if the changeset itself isn't valid (which is pointless).

**Comment by yasserhussain1110** [comment]
@Oxyrus I have modified the code. Please take a look now.

**Comment by Oxyrus** [comment]
It looks way better now @yasserhussain1110 . There is just one thing, you don't need the Repo.insert, because we don't always insert data when using a changeset, we just may see if the data is valid.

**Comment by yasserhussain1110** [comment]
I understand that part @Oxyrus . 

But when we are finally going to insert a user using the `create` method, at that time we'll need to insert, right?

If we just want to create a changeset we'll call `change_user` and **not** call `create`.

If there is something I am not getting, please suggest a way to proceed.

**Comment by Oxyrus** [comment]
Even when we aren't using `create` we still have to validate the data through our changeset, maybe we could have two separate changesets, one which would perform password encryption and one which wouldn't.

Like this

```elixir
def user_changeset(%User{} = user, attrs) do
    user
    |> cast(params, [...])
    |> validate_required([...])
end

def registration_changeset(%User{} = user, attrs) do
    user
    |> user_changeset(attrs)
    |> cast(params, [...])
    |> validate_required([...])
    |> encrypt_password
end
```

**Comment by yasserhussain1110** [comment]
I have made the changes as you suggested. Please have a look.

**Comment by Oxyrus** [comment]
You got rid of your changeset validation, add that again and you're good to go. Here's an implementation:

```elixir
defp encrypt_password(changeset) do
    case changeset do
      %Ecto.Changeset{valid?: true, changes: %{password: password}} ->
        put_change(changeset, :encrypted_password, Comeonin.Bcrypt.hashpwsalt(password))
      _ ->
        changeset
    end
end
```

And just call it inside the pipeline

```elixir
def registration_changeset(%User{} = user, attrs) do
    user
    |> user_changeset(attrs)
    |> encrypt_password
end
```

**Comment by yasserhussain1110** [comment]
That's cool. But I have one question - why should `encrypt_password` function check whether  changeset is valid? It's job is just to `encrypt` right?

I could be wrong about this and you take the call @Oxyrus , but I think the validation check must happen elsewhere.

**Comment by Oxyrus** [comment]
@yasserhussain1110 because if you're encrypting some data that is invalid you're just wasting time.

**Comment by yasserhussain1110** [comment]
@Oxyrus Understood. I think this should do.

**Comment by Oxyrus** [comment]
Awesome @yasserhussain1110 will merge :smile:

**Pull request merged**
